= Contributing
Pivotal AppSuite
:toc: preamble
:toclevels: 1
:!toc-title:
:uri-project: https://github.com/pivotalsoftware/session-managers
:uri-project-issues: {uri-project}/issues
:uri-project-new-issue: {uri-project-issues}/new
:uri-github-pull-requests: https://help.github.com/categories/collaborating-with-issues-and-pull-requests
:uri-github-fork-and-edit: https://github.com/blog/844-forking-with-the-edit-button
:uri-gitscm-rewriting-history: http://git-scm.com/book/en/Git-Tools-Rewriting-History
:uri-gitscm-commit-guideline: https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines
:uri-git-man-page: https://www.kernel.org/pub/software/scm/git/docs/

Have something you'd like to contribute to the test of the manager? We welcome pull requests, but ask that you carefully read this document first to understand how best to submit them; what kind of changes are likely to be accepted; and what to expect from the team when evaluating your submission.

Please refer back to this document as a checklist before issuing any pull request; this will save time for everyone!

== Understanding the Basics

Not sure what a pull request is, or how to submit one?  Take a look at GitHub's excellent {uri-github-pull-requests}[documentation].

== Search Issues First

Is there already an issue that addresses your concern?  Do a bit of searching in our {uri-project-issues}[issue tracker] to see if you can find something similar. If not, please create a {uri-project-new-issue}[new issue] before submitting a pull request unless the change is truly trivial (such as typo fixes or removing compiler warnings).

== Discuss Non-Trivial Contribution Ideas with Committers

If you're considering anything more than correcting a typo or fixing a minor bug, please discuss it in a {uri-project-new-issue}[new issue] before submitting a pull request. We're happy to provide guidance, but please spend an hour or two researching the subject on your own, including searching the mailing list for prior discussions.

== Sign the Contributor License Agreement

Please {uri-project-new-issue}[open an issue] to receive instructions on how to fill out the Contributor License Agreement.

== Use Short Branch Names

Branches used when submitting pull requests should be succinct, lower-case, and dash (-) delimited names (such as `fix-warnings` or `fix-typo`). In {uri-github-fork-and-edit}[fork-and-edit] cases, the GitHub default `patch-1` is fine as well. This is important because branch names show up in the merge commits that result from accepting pull requests.

== Mind the Whitespace

Please carefully follow the whitespace and formatting conventions already present in the code.

* spaces, not tabs
* LF line endings (no CRLF)
* no trailing whitespace

== Add/Update Apache License Header

The Apache License header shall be at the beginning of all source files.

[source,java]
----
/*
 * Copyright (c) 2017 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ...;
----

Always check the date in the license header. For example, if you've modified a file in whose header still reads:
[source,java]
----
/*
 * Copyright (c) 1970 the original author or authors.
 *
----

then please be sure to update it to the current year.

== Squash Commits

Use `git rebase --interactive`, `git add --patch` and other tools to "squash" multiple commits into atomic changes. In addition to the {uri-git-man-page}[`git` man pages], there are many online resources to help you understand how these tools work (try {uri-gitscm-rewriting-history}[this one]).

== Use Real Name in Git Commits

Please configure `git` to use your real first and last name for any commits you intend to submit as pull requests. For example, this is not acceptable:

[source,sh]
----
Author: Nickname <developer@mail.com>
----

Use your first and last name, properly capitalized, as submitted against the Pivotal contributor license agreement:

[source,sh]
----
Author: First Last <developer@mail.com>
----

This helps ensure traceability against the CLA, and also goes a long way to ensuring useful output from tools like `git shortlog`.

You can configure this locally for this repository with:

[source,sh]
----
# from within your local repository
% git config user.name "First Last"
% git config user.email developer@mail.com
----

or globally with:

[source,sh]
----
% git config --global user.name "First Last"
% git config --global user.email developer@mail.com
----

== Format Commit Messages

Please read and follow the {uri-gitscm-commit-guideline}[commit guidelines section of Pro Git].

Most importantly, please format your commit messages in the following way (adapted from the commit template in the above link):

----
Short (50 chars or less) summary of changes

More detailed explanatory text, if necessary. Wrap it to about 72
characters or so. In some contexts, the first line is treated as the
subject of an email and the rest of the text as the body. The blank
line separating the summary from the body is critical (unless you omit
the body entirely); tools like rebase can get confused if you run the
two together.

Further paragraphs come after blank lines.

 - Bullet points are okay, too

 - Typically a hyphen or asterisk is used for the bullet, preceded by a
   single space, with blank lines in between, but conventions vary here

Issue: #10, #11
----

* Use imperative statements in the subject line, e.g. "Fix broken link"
* Begin the subject line sentence with a capitalized verb, e.g. Add, Prune, Fix, Introduce, Avoid
* Do not end the subject line with a period
* Keep the subject line to 50 characters or less
* Wrap lines in the body at 72 characters or less
* Mention associated GitHub issues at the end of the commit comment, prefixed with "Issue: " as above
* In the body of the commit message, explain how things worked before this commit, what has changed, and how things work now

== Run All Tests Prior to Submission

Make sure that all tests pass prior to submitting your pull request.

== Submit Your Pull Request

=== Subject Line

Follow the same conventions for pull request subject lines as described above for commit message subject lines.

=== Body

* Explain your use case. What led you to submit this change? Why were existing mechanisms in the system test insuffiient? Make a case that this is a general-purpose problem and that yours is a general-purpose solution, etc.
* Add any additional information and ask questions; start a conversation, or continue one from GitHub issue
* Also mention that you have submitted the CLA as described above

NOTE: For pull requests containing a single commit, GitHub will default the subject line and body of the pull request to match the subject line and body of the commit message. This is fine, but please also include the items above in the body of the request.

== Expect Discussion and Rework

The Cloud Foundry Java Experience team takes a very conservative approach to accepting contributions to the system test. This is to keep code quality and stability as high as possible, and to keep complexity at a minimum. Your changes, if accepted, may be heavily modified prior to merging. You will retain "Author:" attribution for your Git commits granted that the bulk of your changes remain intact. You may be asked to rework the submission for style (as explained above) and/or substance. Again, we strongly recommend discussing any serious submissions with the Cloud Foundry Java Experience team _prior_ to engaging in serious development work.

Note that you can always force push (`git push -f`) reworked / rebased commits against the branch used to submit your pull request. I.e., you do not need to issue a new pull request when asked to make changes.
